spring:
  application:
    name: helloZuul
    
server:
  port: 8082

zuul:
  routes:
    main:
      path: /**
      serviceId: helloService
      
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://52.86.121.106:8761/eureka/
      