spring:
  application:
    name: zuulServer
    
server:
  port: 8082

zuul:
  routes:
    main:
      path: /**
      serviceId: helloService
#      url: http://52.207.14.13:8081/
      
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://54.172.91.201:8761/eureka/
